### ISSUE TITLE
QC: rename package to gsm.app

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm.app#169]
## QC Details
Standardize naming across packages. Let me know if this is likely to cause problems ...

**Comment by jonthegeek** [comment]
There are things to be careful about, but it should be fine. I have a reaction against periods in package names, but they're growing on me. I'll take this on at some point when Taylor isn't in the middle of anything, because the easiest thing for him to do after it's switched will be to delete his local copy and run `usethis::create_from_github("Gilead-BioStats/gsm.app")` to make sure everything is set up happily.

**Comment by jonthegeek** [comment]
It looks like a global find-and-replace of `gsmApp` to `gsm.app` will be fine. I'll manually clean up the orphaned shinyapps after doing it (and making sure that the prod/dev apps relaunch properly at their new homes). I can run this Tuesday or Wednesday, no prob!
